### ISSUE TITLE
FAQ update

### ISSUE THREAD

**Issue by Eternumkr** [BlixtWallet/blixtwallet.github.io#30]
Connecting Blixt to your own Pi/VM/cloud/packaged/built-from-source node. 

Q: I opened a channel from my blixt to my own node or vice versa but Blixt wallet cant find any routes when I try to pay an invoice. This is my only channel in my Blixt wallet.
A: 1. In your blixt wallet enable "wait for graph sync before paying" in settings. 
    2. (LND nodes only) Ensure you have the following settings,  "numgraphsyncpeers=9" , "ignore-historical-gossip-filters=false" , under "[routing]" section; "routing.strictgraphpruning=false" . *please note for pi users, your startup time will be typically longer and will probably consume more resources with these settings.*  
    3. Open more channels with your Blixt wallet. 
    4. Open more channels on your other node.

**Comment by Darth-Coin** [comment]
Done. Was added here
https://blixtwallet.github.io/faq#home-node-settings
